; ================================================================
; SIH 2026 - Underground Coal Mine Monitoring System
; NODE 1: REFERENCE NODE (MPU6500 ONLY + LoRa SX1278)
; Team Gradient
; ================================================================

[env:esp32node1]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    sandeepmistry/LoRa @ ^0.8.0
    bblanchon/ArduinoJson @ ^7.0.4

build_flags = 
    -DCORE_DEBUG_LEVEL=3
