; ================================================================
; SIH 2026 - Underground Coal Mine Monitoring System
; CENTRAL GATEWAY (LoRa Rx -> WiFi HTTP + Local LED/Buzzer Alerts)
; Team Gradient
; ================================================================

[env:esp32gateway]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    sandeepmistry/LoRa @ ^0.8.0
    bblanchon/ArduinoJson @ ^7.0.4

build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_RUNNING_CORE=1
