; ================================================================
; SIH 2026 - Underground Coal Mine Monitoring System
; NODE 2: MAIN STRATA SUBSIDENCE MONITORING NODE
; Team Gradient
; ================================================================

[env:esp32node2]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    sandeepmistry/LoRa @ ^0.8.0
    stm32duino/STM32duino VL53L4CD @ ^1.0.3
    bogde/HX711 @ ^0.7.5
    bblanchon/ArduinoJson @ ^7.0.4

build_flags = 
    -DCORE_DEBUG_LEVEL=3
