[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    sandeepmistry/LoRa @ ^0.8.0
    adafruit/Adafruit MPU6050 @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    stm32duino/STM32duino VL53L4CD @ ^1.0.3
    bogde/HX711 @ ^0.7.5
    bblanchon/ArduinoJson @ ^7.0.4
